###########
# site.url, site.title

url:   'https://nbisweden.github.io/PythonCourse'

#google_analytics: 'UA-23985298-11'

defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: default
  -
    scope:
      path: "vt17"
    values:
      layout: vt17



########
# more settings

markdown: kramdown

exclude:
- README.md

sass:
  sass_dir: css
  style:    expanded

# pygments: true
# highlighter: rouge

  
# enable vendor prefixes
gems:
  - octopress-autoprefixer
#  - autoprefixer-rails

safe: true
lsi: false
